### PR TITLE
Debug reminder - time passed lesson not removed from reminder

### PR DESCRIPTION
**Pull request by Xiaoyunnn**
// omo I opened the wrong tp folder to create the new branch.

So currently, lessons are considered upcoming by comparing min
For example, date today is 30 Oct 1500

Not upcoming:
1. Date before 30 Oct (has passed)
2. 30 Oct end time before 1500 (has passed)
3. 1 Nov start time after 1500 (beyond 2 days)

Upcoming:
1. 30 Oct end time after or at 1500
2. 31 Oct all day with valid time range
3. 1 Nov start time before or at 1500

Limitation:
- reminder window does not automatically update the list, it only updates when the user keys in `remind` in the command box if no modifications are made to any lesson. (i.e. if the user does nth and just wait for the time to pass, the reminder list does not update upcoming lessons)
- reminder list also updates when `ladd`, `ledit`, `ldelete` are used
 // update on 31 oct 
- allow update with shortcut key and clicking on menu item

### CODE REVIEW

**Review by eeliana — COMMENTED** [review]
Bug here is that if user types `remind` after the lesson has passed, it will indeed get updated but that is not the case if they use the ribbon button (same for both clicking and F5). Both of these actions do not update the reminder list. Only `remind` does.

image

**Comment by lingshanng** [comment]
Add a note in UG

**Review by eeliana — APPROVED** [review]
LGTM

**Review by lingshanng — APPROVED** [review]
LGTM

**Pull request merged**
