### PR TITLE
Disallow empty cancel and uncancel dates

### PR DESCRIPTION
**Pull request by lingshanng**
- fix https://github.com/AY2122S1-CS2103T-F13-3/tp/issues/315

### CODE REVIEW

**Review by Xiaoyunnn — APPROVED** [review]
LGTM

**Comment by eeliana** [comment]
Minor thing but the error message says lesson doesn't happen on 9 dec but it actually does, just that it has already been cancelled?

image

**Review by eeliana — APPROVED** [review]
LGTM

**Comment by lingshanng** [comment]
> Minor thing but the error message says lesson doesn't happen on 9 dec but it actually does, just that it has already been cancelled?

I'll add on in UG

**Pull request merged**
